### ISSUE TITLE
Cannot find module '../grammar.js'

### ISSUE THREAD

**Issue by mrmlnc** [vorpaljs/bash-parser#36]
**Versions:**

  * **Windows 10**
  * **Node.js:** 6.4.0
  * **npm:** 3.10.3
  * **bash-parser:** 0.3.0

Hello,

I installed you package using `npm i bash-parser` on Node.js 6.4.0 and created a simple JS file from your docs:

```js
const parse = require('bash-parser');
const ast = parse('echo foo>file.txt');
```

And after run using `node file.js` I got error:

```
module.js:457
    throw err;
    ^

Error: Cannot find module '../grammar.js'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\projects\nameOfProject\node_modules\bash-parser\src\index.js:5:16)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

**Comment by parro-it** [comment]
I think something goes wrong with my last publish on npm, it skip the grammar file.
I'll publish an updated version tonight

**Comment by parro-it** [comment]
Please check version 0.3.2, the problem should be fixed now.

**Comment by mrmlnc** [comment]
@parro-it, thanks you 💪
